runtime: nodejs20

env_variables:
  NODE_ENV: "production"
  PORT: 8080

handlers:
  - url: /users/.*
    script: auto

  - url: /stuntify/.*
    script: auto

  - url: /stuntify/resep/.*
    script: auto
